server:
  port: 8093
spring:
  application:
    name: nativeconfigserver
  profiles:
    active:
      - native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config