server:
  port: 8094
spring:
  application:
    name: gitconfigserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/stary1993/ordersystem.git
          searchPath: config
          username: stary1993
          password: 19931129jk
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/